In [1]:
import pandas as pd
import numpy as np

In [2]:
text_data = pd.read_csv('../datasets/text_data.csv')

In [3]:
co_multi_label = pd.read_csv('../datasets/co_multi_label.csv')

In [4]:
co = pd.read_csv('../datasets/co.csv')

In [5]:
text_data.head()

,code,label,subcategory,feedback,criticality,organization,question,row_index
0,xn,Couldn't be improved,Nothing to improve,Nothing.,3,Trust A,Trust A - Q1,0
1,ee,Environment/ facilities,Environment/ facilities,Temperature in theatre a little low.,-1,Trust A,Trust A - Q1,1
2,ap,Access,Provision of services,Same service available at Bingham Health Centre.,-2,Trust A,Trust A - Q1,2
3,mi,Communication,Amount/clarity of information,Appointment details given over phone - no phys...,-1,Trust A,Trust A - Q1,3
4,mm,Communication,Communication,On one occasion I was not made aware that my a...,-3,Trust A,Trust A - Q1,4

In [6]:
co.head()

,code,label,subcategory,feedback,criticality,organization,question,row_index
0,sa,Staff,Attitude Of Staff,I phoned the crisis team in the early hours of...,-4,Care Opinion,Care Opinion - Q1,0
1,ds,Dignity,Feeling safe including bullying,The nurses and whole team made me feel safe an...,2,Care Opinion,Care Opinion - Q1,1
2,ss,Staff,Staff: General,Dear Anna (Community Matron) and all staff \n...,3,Care Opinion,Care Opinion - Q1,2
3,cl,Care received,Made A Difference To My Life,To Lesley \nWe wouldn't have managed without ...,4,Care Opinion,Care Opinion - Q1,3
4,co,Care received,1-2-1 care/Time spent with service user,"Thank you Jo, District Nurse, for taking the t...",3,Care Opinion,Care Opinion - Q1,4

In [7]:
co_multi_label.head()

,crit,cat_1,cat_2,cat_3,cat_4,cat_5,cat_6,feedback
0,-4,SA,CE,CS,CR,WA,NaN,I phoned the crisis team in the early hours of...
1,2,DS,SP,SL,NaN,NaN,NaN,The nurses and whole team made me feel safe an...
2,3,SS,NaN,NaN,NaN,NaN,NaN,Dear Anna (Community Matron) and all staff \n...
3,4,CL,SP,NaN,NaN,NaN,NaN,To Lesley \nWe wouldn't have managed without ...
4,3,CO,CP,NaN,NaN,NaN,NaN,"Thank you Jo, District Nurse, for taking the t..."

In [8]:
text_data.label

0           Couldn't be improved
1        Environment/ facilities
2                         Access
3                  Communication
4                  Communication
                  ...
10329              Care received
10330              Care received
10331              Care received
10332                      Staff
10333       Couldn't be improved
Name: label, Length: 10334, dtype: object

In [9]:
counts = pd.DataFrame(text_data.label.value_counts())
counts

                         label
Care received             3363
Staff                     2844
Couldn't be improved      1703
Communication              874
Environment/ facilities    499
Access                     411
Miscellaneous              353
Transition/coordination    145
Dignity                    142

In [10]:
counts['proportion'] = counts['label'] / counts.label.sum()
counts.index.rename('label', inplace=True)
counts.rename(columns = {'label': 'counts'}, inplace=True)
counts

                         counts  proportion
label
Care received              3363    0.325431
Staff                      2844    0.275208
Couldn't be improved       1703    0.164796
Communication               874    0.084575
Environment/ facilities     499    0.048287
Access                      411    0.039772
Miscellaneous               353    0.034159
Transition/coordination     145    0.014031
Dignity                     142    0.013741

In [11]:
text_data.shape

(10334, 8)

In [12]:
co.shape

(1977, 8)

In [13]:
co_multi_label.shape

(1998, 8)

In [14]:
codes = text_data['code'].value_counts()
subcategories = text_data['subcategory'].value_counts()

codes_combined = pd.DataFrame()
codes_combined['code_counts'] = codes
codes_combined['subcategory'] = subcategories.index
codes_combined

    code_counts                                        subcategory
cc         2191                                      Care received
xn         1742                                 Nothing to improve
sa         1321                                  Attitude Of Staff
ss         1103                                     Staff: General
cs          421                                 Advice and support
mi          403                      Amount/clarity of information
sp          374                Professionalism/Competence Of Staff
xe          270                            Everything was good/bad
mm          269                                      Communication
cr          214                             Rules/approach to care
ml          202                                          Listening
ef          189                                               Food
wa          144  Time spent waiting for first appt/referral/ser...
ap          135                              Provision of services
eq          132                               Facilities/equipment
ce          123                                     Emotional care
ee          122                            Environment/ facilities
cp          105                                      Physical care
aa           73                                            General
ca           71                                         Activities
cm           70                                        Medication
co           70            1-2-1 care/Time spent with service user
da           50                     Consistency/Continuity of care
tc           50         Respect For Diversity/ Person-Centeredness
ec           47                                        Cleanliness
cl           46                       Made A Difference To My Life
ti           46                   Coordination/Integration Of Care
sl           46                                    Staffing levels
ds           39                    Feeling safe including bullying
tx           36                           Transition And Discharge
wb           34            Time spent waiting between appointments
ct           30                                          Therapies
dp           25                                           Location
al           25             Involvement: Of Service Users/Patients
dd           23                                   Dignity: General
cf           22                                      Carer support
xm           15                                      Miscellaneous
tt           13                  Transition/ coordination: General
xg           12                                   Nothing was good
ep            9                                  Parking/transport
xf            7                                            Funding
dc            5                                  Leave (under MHA)
xs            5                  Involvement: Of Family And Carers
xl            5                                          Surveying

In [15]:
text_data['criticality'].value_counts()

3      3690
0      2566
2      1053
4       882
-3      787
-2      612
1       282
-1      231
-4      195
-o       21
-9        6
-NA       1
cc        1
SS        1
-6        1
A         1
Name: criticality, dtype: int64